# Generated by Django 4.1.1 on 2022-10-03 10:11

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('job_role', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('birth_date', models.DateTimeField()),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('city', models.CharField(max_length=50)),
                ('skills_desc', models.TextField()),
                ('skill_one', models.CharField(max_length=50)),
                ('skill_two', models.CharField(max_length=50)),
                ('skill_three', models.CharField(max_length=50)),
                ('skill_four', models.CharField(max_length=50)),
                ('skill_five', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
                ('start_year', models.DateTimeField()),
                ('completion_year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250)),
                ('start_year', models.DateTimeField()),
                ('company', models.CharField(max_length=50)),
                ('completion_year', models.DateTimeField()),
                ('role_one', models.TextField()),
                ('role_two', models.TextField()),
                ('role_three', models.TextField()),
                ('role_four', models.TextField()),
            ],
        ),
    ]
