# Generated by Django 4.1.1 on 2022-10-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
