# Generated by Django 4.1.1 on 2022-10-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_about_image_education_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('date_done', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
