# Generated by Django 4.1.1 on 2022-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_project_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(default='Did something cool'),
            preserve_default=False,
        ),
    ]
