# Generated by Django 4.1.1 on 2022-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_project_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project Management', max_length=100),
            preserve_default=False,
        ),
    ]
