# Generated by Django 4.1.1 on 2022-11-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_project_image_project_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
