# Generated by Django 4.1.1 on 2022-11-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_delete_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Job_Experience',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='School',
        ),
    ]
